// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsInSpecTResultsProcessor.ParseInspectSynFileEntry(System.String,System.Collections.Generic.IDictionary{PHRPReader.clsPHRPParserInspect.InspectSynFileColumns,System.Int32},PeptideHitResultsProcessor.clsSearchResultsInSpecT,System.String@,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsMODaResultsProcessor.ParseMODaSynFileEntry(System.String,PeptideHitResultsProcessor.clsSearchResultsMODa,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.clsPHRPParserMODa.MODaSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsMODPlusResultsProcessor.ParseMODPlusSynFileEntry(System.String,PeptideHitResultsProcessor.clsSearchResultsMODPlus,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.clsPHRPParserMODPlus.MODPlusSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsMSAlignResultsProcessor.ParseMSAlignSynFileEntry(System.String,PeptideHitResultsProcessor.clsSearchResultsMSAlign,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.clsPHRPParserMSAlign.MSAlignSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsMSGFPlusResultsProcessor.ParseMSGFPlusSynFileEntry(System.String,PeptideHitResultsProcessor.clsSearchResultsMSGFPlus,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.clsPHRPParserMSGFPlus.MSGFPlusSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsPHRPBaseClass.AutoDefinePeptideHitResultsFilePath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsPHRPBaseClass.CloseSequenceOutputFiles")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsPHRPBaseClass.DeleteFileIgnoreErrors(System.String)")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsSearchResultsBaseClass.SequenceWithPrefixAndSuffix(System.Boolean)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsTopPICResultsProcessor.ParseTopPICSynFileEntry(System.String,PeptideHitResultsProcessor.clsSearchResultsTopPIC,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.clsPHRPParserTopPIC.TopPICSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsXTandemResultsProcessor.InitializeRegExObjects")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsXTandemResultsProcessor.ParseXTandemResultsFileEntry(System.Xml.XmlReader,System.IO.StreamWriter,System.Collections.Generic.IList{PeptideHitResultsProcessor.clsSearchResultsXTandem},System.String@,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsInSpecTResultsProcessor.ComputePeptideMHFromPrecursorInfo(System.String,System.String,System.String)~System.Double")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsMSGFPlusResultsProcessor.MSGFPlusResultPassesSynFilter(PeptideHitResultsProcessor.clsMSGFPlusResultsProcessor.udtMSGFPlusSearchResultType)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsPHRPBaseClass.CreateProteinModDetailsFile(System.String,System.String,System.String,PHRPReader.clsPHRPReader.peptideHitResultType)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsPHRPBaseClass.PeptideToProteinMapper_ProgressChanged(System.String,System.Single)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsPHRPBaseClass.ShowPeriodicWarning(System.Int32,System.Int32,System.String)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsXTandemResultsProcessor.XMLTextReaderGetInnerText(System.Xml.XmlReader)~System.String")]
