// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Keep for reference", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Data.SequestResults.ComputePeptideXCorrNext")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Data.SearchResultsBaseClass.SequenceWithPrefixAndSuffix(System.Boolean)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.InSpecTResultsProcessor.ParseInspectSynFileEntry(System.String,System.Collections.Generic.IDictionary{PHRPReader.Data.InspectSynFileColumns,System.Int32},PeptideHitResultsProcessor.Data.InSpecTResults,System.Collections.Generic.ICollection{System.String},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MODaResultsProcessor.ParseMODaSynFileEntry(System.String,PeptideHitResultsProcessor.Data.MODaResults,System.Collections.Generic.ICollection{System.String},System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Data.MODaSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MODPlusResultsProcessor.ParseMODPlusSynFileEntry(System.String,PeptideHitResultsProcessor.Data.MODPlusResults,System.Collections.Generic.ICollection{System.String},System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Data.MODPlusSynFileColumns,System.Int32})~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MSAlignResultsProcessor.ParseMSAlignSynFileEntry(System.String,PeptideHitResultsProcessor.Data.MSAlignResults,System.Collections.Generic.ICollection{System.String},System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Data.MSAlignSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MSGFPlusResultsProcessor.ParseMSGFPlusSynFileEntry(System.String,PeptideHitResultsProcessor.Data.MSGFPlusResults,System.Collections.Generic.ICollection{System.String},System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Data.MSGFPlusSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.AutoDefinePeptideHitResultsFilePath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.CloseSequenceOutputFiles")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.DeleteFileIgnoreErrors(System.String)")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.TopPICResultsProcessor.ParseTopPICSynFileEntry(System.String,PeptideHitResultsProcessor.Data.TopPICResults,System.Collections.Generic.ICollection{System.String},System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Data.TopPICSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.XTandemResultsProcessor.InitializeRegExObjects")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.XTandemResultsProcessor.ParseXTandemResultsFileEntry(System.Xml.XmlReader,System.IO.StreamWriter,System.Collections.Generic.IList{PeptideHitResultsProcessor.Data.XTandemResults},System.Collections.Generic.ICollection{System.String},System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Data.SequestResults.ComputePeptideXCorrNext")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.InSpecTResultsProcessor.ComputePeptideMHFromPrecursorInfo(System.String,System.String,System.String)~System.Double")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MSGFPlusResultsProcessor.MSGFPlusResultPassesSynFilter(PeptideHitResultsProcessor.Processor.MSGFPlusResultsProcessor.MSGFPlusSearchResult)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.PeptideToProteinMapper_ProgressChanged(System.String,System.Single)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.ShowPeriodicWarning(System.Int32,System.Int32,System.String)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.TopPICResultsProcessor.StoreSynMatches(System.Collections.Generic.IList{PeptideHitResultsProcessor.Processor.TopPICResultsProcessor.TopPICSearchResult},System.Int32,System.Int32,System.Collections.Generic.ICollection{PeptideHitResultsProcessor.Processor.TopPICResultsProcessor.TopPICSearchResult},System.Boolean)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.XTandemResultsProcessor.XMLTextReaderGetInnerText(System.Xml.XmlReader)~System.String")]
[assembly: SuppressMessage("Redundancy", "RCS1213:Remove unused member declaration.", Justification = "Keep for reference", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Data.SequestResults.ComputePeptideXCorrNext")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MODaResultsProcessor.LoadMGFIndexToScanMapFile(System.IO.FileInfo)~System.Boolean")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.StringUtilities.LongestCommonStringFromStart(System.Collections.Generic.List{System.String},System.Boolean)~System.String")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.StringUtilities.LongestCommonStringFromStartVerbose(System.Collections.Generic.List{System.String},System.Boolean)~System.String")]
