// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Keep for reference", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Data.SequestResults.ComputePeptideXCorrNext")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.clsPHRPBaseClass.AutoDefinePeptideHitResultsFilePath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Data.SearchResultsBaseClass.SequenceWithPrefixAndSuffix(System.Boolean)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.InSpecTResultsProcessor.ParseInspectSynFileEntry(System.String,System.Collections.Generic.IDictionary{PHRPReader.Reader.InspectSynFileReader.InspectSynFileColumns,System.Int32},PeptideHitResultsProcessor.Data.InSpecTResults,System.String@,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MODaResultsProcessor.ParseMODaSynFileEntry(System.String,PeptideHitResultsProcessor.Data.MODaResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Reader.MODaSynFileReader.MODaSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MODPlusResultsProcessor.ParseMODPlusSynFileEntry(System.String,PeptideHitResultsProcessor.Data.MODPlusResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Reader.MODPlusSynFileReader.MODPlusSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MSAlignResultsProcessor.ParseMSAlignSynFileEntry(System.String,PeptideHitResultsProcessor.Data.MSAlignResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Reader.MSAlignSynFileReader.MSAlignSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MSGFPlusResultsProcessor.ParseMSGFPlusSynFileEntry(System.String,PeptideHitResultsProcessor.Data.MSGFPlusResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Data.MSGFPlusSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.TopPICResultsProcessor.ParseTopPICSynFileEntry(System.String,PeptideHitResultsProcessor.Data.TopPICResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Reader.TopPICSynFileReader.TopPICSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "<Pending>", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.XTandemResultsProcessor.ParseXTandemResultsFileEntry(System.Xml.XmlReader,System.IO.StreamWriter,System.Collections.Generic.IList{PeptideHitResultsProcessor.Data.XTandemResults},System.String@,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.MSAlignResultsProcessor.ParseMSAlignSynFileEntry(System.String,PeptideHitResultsProcessor.MSAlignResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Reader.MSAlignSynFileReader.MSAlignSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.InSpecTResultsProcessor.ParseInspectSynFileEntry(System.String,System.Collections.Generic.IDictionary{PHRPReader.Reader.InspectSynFileReader.InspectSynFileColumns,System.Int32},PeptideHitResultsProcessor.InSpecTResults,System.String@,System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.AutoDefinePeptideHitResultsFilePath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.CloseSequenceOutputFiles")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.DeleteFileIgnoreErrors(System.String)")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.TopPICResultsProcessor.ParseTopPICSynFileEntry(System.String,PeptideHitResultsProcessor.TopPICResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Reader.TopPICSynFileReader.TopPICSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.XTandemResultsProcessor.InitializeRegExObjects")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.XTandemResultsProcessor.ParseXTandemResultsFileEntry(System.Xml.XmlReader,System.IO.StreamWriter,System.Collections.Generic.IList{PeptideHitResultsProcessor.XTandemResults},System.String@,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.SearchResultsBaseClass.SequenceWithPrefixAndSuffix(System.Boolean)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessorProcessor.MODaResultsProcessor.ParseMODaSynFileEntry(System.String,PeptideHitResultsProcessor.MODaResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Reader.MODaSynFileReader.MODaSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessorProcessor.MODPlusResultsProcessor.ParseMODPlusSynFileEntry(System.String,PeptideHitResultsProcessor.MODPlusResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.Reader.MODPlusSynFileReader.MODPlusSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Allowed", Scope = "member", Target = "~M:PeptideHitResultsProcessorProcessor.MSGFPlusResultsProcessor.ParseMSGFPlusSynFileEntry(System.String,PeptideHitResultsProcessor.MSGFPlusResults,System.String@,System.Int32,System.Collections.Generic.IDictionary{PHRPReader.REader.MSGFPlusSynFileReader.MSGFPlusSynFileColumns,System.Int32},System.String@)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor..ProcessorMSGFPlusResultsProcessor.MSGFPlusResultPassesSynFilter(PeptideHitResultsProcessor.MSGFPlusResultsProcessor.udtMSGFPlusSearchResultType)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.InSpecTResultsProcessor.ComputePeptideMHFromPrecursorInfo(System.String,System.String,System.String)~System.Double")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.PeptideToProteinMapper_ProgressChanged(System.String,System.Single)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.PHRPBaseClass.ShowPeriodicWarning(System.Int32,System.Int32,System.String)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.XTandemResultsProcessor.XMLTextReaderGetInnerText(System.Xml.XmlReader)~System.String")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:PeptideHitResultsProcessor.SequestResults.ComputePeptideXCorrNext")]
[assembly: SuppressMessage("Redundancy", "RCS1213:Remove unused member declaration.", Justification = "Keep for reference", Scope = "member", Target = "~M:PeptideHitResultsProcessor.SequestResults.ComputePeptideXCorrNext")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "Keep to aid with debugging", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MSPathFinderResultsProcessor.ParseMSPathFinderResultsFileEntry(System.String,PeptideHitResultsProcessor.MSPathFinderResultsProcessor.udtMSPathFinderSearchResultType@,System.String@,System.Collections.Generic.IDictionary{PeptideHitResultsProcessor.MSPathFinderResultsProcessor.MSPathFinderResultsFileColumns,System.Int32},System.Collections.Generic.IReadOnlyCollection{PHRPReader.MSGFPlusParamFileModExtractor.udtModInfoType},System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:PeptideHitResultsProcessor.Processor.MODaResultsProcessor.LoadMGFIndexToScanMapFile(System.IO.FileInfo)~System.Boolean")]
